### ISSUE TITLE
obj_extend is not defined

### ISSUE THREAD

**Issue by donaldpipowitch** [tenbits/selenium-query#1]
When using this module I get `obj_extend is not defined`. E.g.
````
import $ from 'selenium-query';
global.$ = $(driver);

# /node_modules/selenium-query/lib/query.js:1076
# obj_extend(SQueryProto, {
# ^
# 
# ReferenceError: obj_extend is not defined
````

You probably need to set `_.` before `obj_extend` (at least in 2 places).

**Comment by tenbits** [comment]
@donaldpipowitch, sorry. Yes, we are using the module in the internal environment, so the utils are globally available. The issue should be fixed now, I have also updated the npm repo. If you find any further issues, I'll be glad to fix them ;)

**Comment by donaldpipowitch** [comment]
Found further issues :D Thank you for the quick fix!
