### ISSUE TITLE
Cannot read property 'done' of undefined

### ISSUE THREAD

**Issue by donaldpipowitch** [tenbits/selenium-query#2]
Thank you for the bug fix in #1. Now I get:

````
    TypeError: Cannot read property 'done' of undefined
        at async_each (/node_modules/selenium-query/lib/query.js:143:7)
````

**Comment by tenbits** [comment]
Hm, I cannt reproduce the issue. Could you please send the code snippet that you use. Or it is the same as in #1? Do you properly build the `driver` and load the page before passing it into `$`? _Please also update the package from npm once again_ You can also take a look into the tests and look how to build the webdriver before: [utils.js](/tenbits/selenium-query/blob/master/test/utils.js)

_Thanks for posting the issues ;)_

**Comment by donaldpipowitch** [comment]
Hi, I've updated the module. My code looks like this:

````
// setup
import driver from 'selenium-webdriver';
import SQuery from 'selenium-query';

let browser = new driver.Builder()
  .forBrowser('firefox', '36')
  .usingServer('http://foo:1337/wd/hub')
  .build();

// global helper
global.driver = driver;
global.browser = browser;
global.$ = new SQuery(browser).find;

// other stuff following...
````

````
// test could look like this
describe('cost types', function() {
  beforeEach(async function() {
    browser.get('https://example.com/login');
    browser.manage().window().maximize();
    $('input[name=login]').sendKeys('e2e-example');
    $('input[name=password]').sendKeys('e2e-example');
    $('input[type=submit]').click();
    await browser.sleep(2000);
  });

  it('should let me delete cost types', async function() {
    let text = await $('.section h1').text();
    expect(text).toBe('foo');
});
````

**Comment by donaldpipowitch** [comment]
> load the page before passing it into

Oh! I didn't do that. I'll try it.

**Comment by donaldpipowitch** [comment]
Works.

**Comment by tenbits** [comment]
I'm glad, that it works :) If you find any issues, please report, and I'll fix them asap. Or if you want to have any features, I'll add them eagerly. Cheers, Alex
