### ISSUE TITLE
 TypeError: $ is not a function

### ISSUE THREAD

**Issue by serdarde** [tenbits/selenium-query#4]
I have just copied code from your docu:

    const $ = require('selenium-query');
    $(driver).find('button.L3NKy').attr('type', 'button').click();

And this is the log I receive:

    TypeError: $ is not a function

I have tried version v0.51.50 and v0.51.52

**Comment by tenbits** [comment]
Thank you for reporting this, I'm rewriting the engine a little bit, to support different driver abstractions, e.g. right now also `jsdom` is supported, to make the queries even faster, when the full browser driver is not required. And I have missed the correct export format. It is fixed now  in `0.51.56`.

**Comment by serdarde** [comment]
Thanks for the update. I haven't tried yet but the library looks really useful 👍
